# This workflow will do a clean install of node dependencies and run tests

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and run tests
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - run: yarn install --immutable --silent --non-interactive 2> >(grep -v warning 1>&2)
      - run: yarn lint
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and run tests
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - run: yarn install --immutable --silent --non-interactive 2> >(grep -v warning 1>&2)
      - run: yarn e2e
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
