# This workflow will do a clean install of node dependencies and run tests

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js and run tests
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.x
    - run: yarn install --immutable --silent --non-interactive
    - run: yarn lint
    - run: yarn test

